# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-26 05:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='model_pic',
        ),
        migrations.AddField(
            model_name='imageuploadmodel',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imageuploadmodel',
            name='document',
            field=models.FileField(default='default', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='imageuploadmodel',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 26, 5, 33, 56, 347243, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
