# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-26 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20170426_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='document',
        ),
        migrations.AddField(
            model_name='imageuploadmodel',
            name='model_pic',
            field=models.ImageField(default='default', upload_to='documents/'),
        ),
    ]
