# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-26 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20170426_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='model_pic',
            field=models.ImageField(default='none', upload_to='documents/'),
        ),
    ]
