# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20170426_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageuploadmodel',
            old_name='model_pic',
            new_name='picArray',
        ),
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='uploaded_at',
        ),
    ]
