# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_imageuploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='picArray',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.imageUploaded'),
        ),
    ]
