# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20170502_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='picArray',
        ),
        migrations.AddField(
            model_name='imageuploadmodel',
            name='ModelPic',
            field=models.ImageField(default='none', upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='imageUploaded',
        ),
    ]
