# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_auto_20170502_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageuploadmodel',
            old_name='ModelPic',
            new_name='upload',
        ),
    ]
